"""add nested folder support

Revision ID: 5d2e8a6ff8de
Revises: 6b1fc698f6df
Create Date: 2026-09-04 15:14:02.800916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2e8a6ff8de'
down_revision: Union[str, Sequence[str], None] = '6b1fc698f6df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('folders', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.add_column('folders', sa.Column('color', sa.String(length=30), nullable=True))
    op.alter_column('folders', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_folders_owner_id'), table_name='folders')
    op.create_index(op.f('ix_folders_parent_id'), 'folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_folders_user_id'), 'folders', ['user_id'], unique=False)
    op.drop_constraint(op.f('folders_owner_id_fkey'), 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'folders', 'folders', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('folders', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.create_foreign_key(op.f('folders_owner_id_fkey'), 'folders', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_folders_user_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_parent_id'), table_name='folders')
    op.create_index(op.f('ix_folders_owner_id'), 'folders', ['owner_id'], unique=False)
    op.alter_column('folders', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('folders', 'color')
    op.drop_column('folders', 'parent_id')
    op.drop_column('folders', 'user_id')
    # ### end Alembic commands ###
