"""expand note model

Revision ID: 6b1fc698f6df
Revises: 372d99db2a45
Create Date: 2026-09-01 21:41:14.361785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1fc698f6df'
down_revision: Union[str, Sequence[str], None] = '372d99db2a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('notes', sa.Column('excerpt', sa.String(length=500), nullable=True))
    op.add_column('notes', sa.Column('is_favorite', sa.Boolean(), nullable=False))
    op.add_column('notes', sa.Column('color', sa.String(length=30), nullable=True))
    op.add_column('notes', sa.Column('status', sa.String(length=30), nullable=False))
    op.alter_column('notes', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.drop_index(op.f('ix_notes_is_archived'), table_name='notes')
    op.drop_index(op.f('ix_notes_is_deleted'), table_name='notes')
    op.drop_index(op.f('ix_notes_is_pinned'), table_name='notes')
    op.drop_index(op.f('ix_notes_owner_id'), table_name='notes')
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.drop_constraint(op.f('notes_owner_id_fkey'), 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notes', 'is_deleted')
    op.drop_column('notes', 'content_type')
    op.drop_column('notes', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('notes', sa.Column('content_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('notes', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('notes_owner_id_fkey'), 'notes', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.create_index(op.f('ix_notes_owner_id'), 'notes', ['owner_id'], unique=False)
    op.create_index(op.f('ix_notes_is_pinned'), 'notes', ['is_pinned'], unique=False)
    op.create_index(op.f('ix_notes_is_deleted'), 'notes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_notes_is_archived'), 'notes', ['is_archived'], unique=False)
    op.alter_column('notes', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('notes', 'status')
    op.drop_column('notes', 'color')
    op.drop_column('notes', 'is_favorite')
    op.drop_column('notes', 'excerpt')
    op.drop_column('notes', 'user_id')
    # ### end Alembic commands ###
