"""add note full text search

Revision ID: c4e4c72166d5
Revises: 7dede2cdddc0
Create Date: 2026-09-04 19:25:48.837161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4e4c72166d5'
down_revision: Union[str, Sequence[str], None] = '7dede2cdddc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('notes', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(content, ''))", persisted=True), nullable=False))
    # op.create_index('ix_notes_search_vector', 'notes', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column(
        "notes",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', "
                "coalesce(title, '') || ' ' || "
                "coalesce(content, ''))",
                persisted=True,
            ),
            nullable=True,
        ),
    )

    op.create_index(
        "ix_notes_search_vector",
        "notes",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_notes_search_vector', table_name='notes', postgresql_using='gin')
    # op.drop_column('notes', 'search_vector')
    op.drop_index(
        "ix_notes_search_vector",
        table_name="notes",
    )

    op.drop_column(
        "notes",
        "search_vector",
    )
    # ### end Alembic commands ###
